# Generated by Django 3.1.2 on 2020-11-21 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
